version: '2'
services:
  michel-nginx:
    image: jwilder/nginx-proxy
    container_name: michel
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/conf.d"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "./conf/proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro"
#      - "PATH_TO_PASSWORDS:/etc/nginx/htpasswd"
#      - "PATH_TO_CERTS/certs:/etc/nginx/certs:ro"
#      - "PATH_TO_CUSTOM_CONFIG:/etc/nginx/conf.d/custom.conf:ro"
    networks:
      - nginx-proxy

  michel-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    container_name: michel-letsencrypt
    volumes_from:
      - michel-nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./conf/nginx_location.conf:/app/nginx_location.conf"
#      - "PATH_TO_CERTS/certs:/etc/nginx/certs:rw"
    networks:
      - nginx-proxy
#    environment:
#     - ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
